/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.razu.client;

/**
 *
 * @author abdur
 */
public class NewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public NewJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        InvitationPanel = new jpanelcustom.JPanelCz();
        AcceptRequestButton = new javax.swing.JButton();
        DenyRequestButton = new javax.swing.JButton();
        RequestLabel = new org.jdesktop.swingx.JXLabel();

        InvitationPanel.setBackground(new java.awt.Color(204, 0, 0));
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder1 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder1.setCornerSize(20);
        dropShadowBorder1.setShadowColor(new java.awt.Color(204, 0, 0));
        dropShadowBorder1.setShadowSize(10);
        dropShadowBorder1.setShowLeftShadow(true);
        dropShadowBorder1.setShowTopShadow(true);
        InvitationPanel.setBorder(dropShadowBorder1);
        InvitationPanel.setPreferredSize(new java.awt.Dimension(100, 100));

        AcceptRequestButton.setFont(new java.awt.Font("Lucida Calligraphy", 1, 13)); // NOI18N
        AcceptRequestButton.setForeground(new java.awt.Color(0, 153, 77));
        AcceptRequestButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/razu/client/Images/raccept.png"))); // NOI18N
        AcceptRequestButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AcceptRequestButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AcceptRequestButtonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                AcceptRequestButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                AcceptRequestButtonMouseReleased(evt);
            }
        });
        AcceptRequestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcceptRequestButtonActionPerformed(evt);
            }
        });

        DenyRequestButton.setFont(new java.awt.Font("Lucida Calligraphy", 1, 13)); // NOI18N
        DenyRequestButton.setForeground(new java.awt.Color(190, 23, 29));
        DenyRequestButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/razu/client/Images/rdeny.png"))); // NOI18N
        DenyRequestButton.setOpaque(false);
        DenyRequestButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DenyRequestButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DenyRequestButtonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                DenyRequestButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                DenyRequestButtonMouseReleased(evt);
            }
        });
        DenyRequestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DenyRequestButtonActionPerformed(evt);
            }
        });

        RequestLabel.setForeground(new java.awt.Color(255, 255, 255));
        RequestLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RequestLabel.setText("You along with razu0031, rafi 0051, nayeem109 are requested to play by frahad1220");
        RequestLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        RequestLabel.setAlignmentY(0.0F);
        RequestLabel.setAutoscrolls(true);
        RequestLabel.setFont(new java.awt.Font("Lucida Calligraphy", 0, 18)); // NOI18N
        RequestLabel.setIconTextGap(0);
        RequestLabel.setLineWrap(true);
        RequestLabel.setTextAlignment(org.jdesktop.swingx.JXLabel.TextAlignment.CENTER);

        javax.swing.GroupLayout InvitationPanelLayout = new javax.swing.GroupLayout(InvitationPanel);
        InvitationPanel.setLayout(InvitationPanelLayout);
        InvitationPanelLayout.setHorizontalGroup(
            InvitationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InvitationPanelLayout.createSequentialGroup()
                .addGroup(InvitationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InvitationPanelLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(AcceptRequestButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88)
                        .addComponent(DenyRequestButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(InvitationPanelLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(RequestLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        InvitationPanelLayout.setVerticalGroup(
            InvitationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InvitationPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(RequestLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(InvitationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DenyRequestButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AcceptRequestButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 398, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 11, Short.MAX_VALUE)
                    .addComponent(InvitationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 12, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(InvitationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void AcceptRequestButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AcceptRequestButtonMouseEntered
        AcceptRequestButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/razu/client/Images/raccept2.png")));
    }//GEN-LAST:event_AcceptRequestButtonMouseEntered

    private void AcceptRequestButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AcceptRequestButtonMouseExited
        AcceptRequestButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/razu/client/Images/raccept.png")));
    }//GEN-LAST:event_AcceptRequestButtonMouseExited

    private void AcceptRequestButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AcceptRequestButtonMousePressed
        AcceptRequestButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/razu/client/Images/raccept.png")));
    }//GEN-LAST:event_AcceptRequestButtonMousePressed

    private void AcceptRequestButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AcceptRequestButtonMouseReleased
        AcceptRequestButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/razu/client/Images/raccept2.png")));
    }//GEN-LAST:event_AcceptRequestButtonMouseReleased

    private void AcceptRequestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcceptRequestButtonActionPerformed

    }//GEN-LAST:event_AcceptRequestButtonActionPerformed

    private void DenyRequestButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DenyRequestButtonMouseEntered
        DenyRequestButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/razu/client/Images/rdeny2.png")));
    }//GEN-LAST:event_DenyRequestButtonMouseEntered

    private void DenyRequestButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DenyRequestButtonMouseExited
        DenyRequestButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/razu/client/Images/rdeny.png")));
    }//GEN-LAST:event_DenyRequestButtonMouseExited

    private void DenyRequestButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DenyRequestButtonMousePressed
        DenyRequestButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/razu/client/Images/rdeny.png")));
    }//GEN-LAST:event_DenyRequestButtonMousePressed

    private void DenyRequestButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DenyRequestButtonMouseReleased
        DenyRequestButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/razu/client/Images/rdeny2.png")));
    }//GEN-LAST:event_DenyRequestButtonMouseReleased

    private void DenyRequestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DenyRequestButtonActionPerformed
        this.getParent().getParent().hide();
        System.out.print(this.getParent().getName());
        //this.setVisible(false);
    }//GEN-LAST:event_DenyRequestButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AcceptRequestButton;
    private javax.swing.JButton DenyRequestButton;
    private jpanelcustom.JPanelCz InvitationPanel;
    private org.jdesktop.swingx.JXLabel RequestLabel;
    // End of variables declaration//GEN-END:variables
}
